### PR TITLE
Add "Dark" theme

### PR DESCRIPTION
**Pull request by Shuja-Mahmood**
Added "Dark" theme.

This has a dark grey accent colour and is darker than the "default" dark theme. Also increased the font size.

### CODE REVIEW

**Comment by m4heshd** [comment]
Unfortunately you can't have a CSS file inside the theme. You're welcome to update the pull by removing it.

**Review by m4heshd — CHANGES_REQUESTED** [review]
Unfortunately you can't have a CSS file inside the theme. You're welcome to update the pull by removing it.

**Comment by Shuja-Mahmood** [comment]
Removing the CSS file will make some elements of WhatsApp app hidden as they will have the same colour as the background, therefore I'm removing the theme. Thanks for your time considering it.

**Comment by m4heshd** [comment]
You actually gave me an idea to further improve theme customization. I might push an update to support this structure in the next release. If that happens, I'll be reopening this PR for merge. Meanwhile, don't be discouraged to contribute to the project in any way you prefer. If you do plan on contributing, introducing yourself on the Telegram chat would be a huge +1.

**Comment by Shuja-Mahmood** [comment]
Thank you for the encouraging words. Considering that I'm still an undergraduate and have zero knowledge of how things are done, I don't think I'll be of much help.

Anyways this is not the end of my contributions to this project. I'll be looking forward to the new customisation and features.

**Comment by m4heshd** [comment]
Glad to know you'll be actively supporting.

**Pull request closed without merging**
