### PR TITLE
fix: macOS color fix for v0.4.315

### PR DESCRIPTION
**Pull request by firefinchdev**

### CODE REVIEW

**Comment by firefinchdev** [comment]
Solves #114

**Review by jorgebirck — COMMENTED** [review]
You changed all the lines, can you please change only the one that really need to be changed?

Thanks in advance.

**Comment by firefinchdev** [comment]
Actually, I just replaced the css file with the one available at https://userstyles.org/styles/142096/dark-whatsapp-theme-by-mew?utm_campaign=stylish_stylepage

**Comment by firefinchdev** [comment]
And it restores the exact dark mode it should be...

**Comment by firefinchdev** [comment]
Closing since the solution does not work anywhere. Applying the solution now shows an update dialog (See https://github.com/m4heshd/whatsapp-desktop-dark/issues/114#issuecomment-580126113)

**Pull request closed without merging**
